#!/usr/bin/env bash
# Displays "to inifity and beyond" or "I am invincible!!!" when receiving a SIGTERM signal
handle_sigterm()
{
	echo "I am invincible!!!"
}

trap handle_sigterm SIGTERM

while true
do
	echo "To inifinity and beyond"
	sleep 2
done
