#!/usr/bin/env bash
# Displays Fizz multiples of 3, Buzz multiples of 5, FizzBuzz for both otherwise the number
for number in {1..100}; do
    if ((number % 3 == 0)) && ((number % 5 == 0)); then
        echo "FizzBuzz"
    elif ((number % 3 == 0)); then
        echo "Fizz"
    elif ((number % 5 == 0)); then
        echo "Buzz"
    else
        echo "$number"
    fi
done
