#!/usr/bin/env bash
# Groups visitors by IP and HTTP status code, and displays this data.
log_file="./apache-access.log"

awk -F ' ' '{print $1, $9}' "$log_file" | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'
