#!/usr/bin/env bash
# Displaying 1 - 20, after 4, 9, 17 "bad luck from China/Japan/Italy" 
count=1

while [ $count -le 20 ]
do
	echo "$count"

	case $count in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	count=$((count + 1))
	
done
