#!/usr/bin/env bash
# Displaying Hours from 0 - 12 and Minutes from 1 - 59
hour=0

while [ $hour -le 12 ]
do
	minute=1
	echo "hour: $hour"
	if [ $hour -eq 12 ]
	then
		break
	else
		while [ $minute -le 59 ]
		do
			echo $minute
			minute=$((minute + 1))
		done
	fi
	hour=$((hour + 1))
done
