#!/usr/bin/env bash
# Displays what is in the current directory
for file in *
do
	if [[ $file != .* ]]
	then
		name="${file#-}"
		clean_name="${name##*[0-9]-}"
		printf "%s " $clean_name
	fi
done
echo ""
