#!/usr/bin/env bash
# This script configures an Ubuntu server localhost and facebook.com
new_local_ip="127.0.0.2"
new_facebook_ip="8.8.8.8"

update_host_entry()
{
	local host_ip="$1"
	local host_name="$2"
	if grep -q "$host_name" /etc/hosts
	then
		sed -i -E "s/^\S+\s+$host_name$/$host_ip $host_name/" /etc/hosts
	else
		sh -c "echo '$host_ip $host_name' >> /etc/hosts"
	fi
}

update_host_entry "$new_local_ip" "localhost"
update_host_entry "$new_facebook_ip" "facebook.com"
